package studentOrientation.courseRegistration;

import studentOrientation.activityExpenses.CaloriesI;
import studentOrientation.activityExpenses.CarbonCostI;
import studentOrientation.activityExpenses.CurrencyCostI;
import studentOrientation.activityExpenses.DurationI;

public class OfflineCourseRegistration implements CourseRegistrationI,CaloriesI,CarbonCostI,CurrencyCostI,DurationI{

}
